version: '3.8'

services:
  python-backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./python:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  node-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
      - "5555:5555"
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db-data: