version: '3.8'

services:
  python-backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./python:/usr/src/app

  node-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ./node:/usr/src/app

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
